plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.app_marifin_javadroid'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.example.app_marifin_javadroid"
        minSdk 26
        targetSdk 37
        versionCode 4
        versionName "1.3.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    // AndroidX & Material UI
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.recyclerview
    implementation libs.viewpager2
    implementation libs.swiperefreshlayout

    // Lifecycle & Architecture Components
    implementation libs.lifecycle.viewmodel
    implementation libs.lifecycle.livedata
    implementation libs.lifecycle.runtime
    implementation libs.navigation.fragment
    implementation libs.navigation.ui

    // Local Database (Room)
    implementation libs.room.runtime
    annotationProcessor libs.room.compiler

    // Secure Storage
    implementation libs.security.crypto

    // Networking & Serialization
    implementation libs.retrofit
    implementation libs.retrofit.gson
    implementation libs.okhttp
    implementation libs.okhttp.logging
    implementation libs.gson

    // Image & Charts
    implementation libs.glide
    annotationProcessor libs.glide.compiler
    implementation libs.mpandroidchart

    // Background Tasks
    implementation libs.work.runtime

    // Unit Testing
    testImplementation libs.junit
    testImplementation libs.mockito.core
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}